on: [push]

name: Continuous integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          echo build
          cargo install mdbook
          cd companion-book
          mdbook build
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'companion-book/book'
          target-directory: 'rust'
          destination-github-username: 'newca12'
          destination-repository-name: 'newca12.github.com'
          user-email: newca12@users.noreply.github.com
          commit-message: Update gallery-rs companion book
          target-branch: master